name: GraalVM Native Image builds
on: [pull_request]
jobs:
  build:
    name: executable for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: call gradle native build command
        run: |
          ./gradlew -Pagent :cli:nativeCompile
          ./gradlew :cli:metadataCopy --task run --dir /src/main/resources/META-INF/native-image
      
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: move-${{ matrix.os }}
          path: ${{ github.workspace }}/cli/build/native/nativeCompile/move*
          compression: 9
          if-no-files-found: error
